language: python
python:
    - "2.7"
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/random.ino
    - PLATFORMIO_CI_SRC=examples/sign.ino
install:
    - pip install -U platformio
script:
    - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560
